spring.application.name=workflow


spring.datasource.url=jdbc:mysql://localhost:3306/workflow_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=wngM1Ujxu/0f+VL7qrlzF2lmU228bYjF5dBi5ck4Bo4=

jwt.expiration=3600000